### ISSUE TITLE
Weak Order 2.0 SRK methods

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/StochasticDiffEq.jl#182]
- [x] Ito DRI1 https://www.sciencedirect.com/science/article/pii/S0168927408000482 or https://arxiv.org/abs/1303.5103
- [x] Older ito: https://www.jstor.org/stable/27862707?seq=1
  - [x] RI1
  - [x] RI3
  - [x] RI5
  - [x] RI6
- [x] PL1WM from Kloeden and Platen
- [x] NON https://www.sciencedirect.com/science/article/pii/S0377042706003906
- [x] NON2 https://www.sciencedirect.com/science/article/pii/S0377042711002159
- [x] COM https://www.sciencedirect.com/science/article/pii/S0377042706001737?via%3Dihub
- [x] https://arxiv.org/pdf/1303.4510
  - [x] RDI1WM
  - [x] RDI2WM
  - [x] RDI3WM 
  - [x] RDI4WM
- [x] SIE / SME https://epubs.siam.org/doi/pdf/10.1137/S1064827501387814
  - [x] SIE-A
  - [x] SME-A
  - [x] SIE-B
  - [x] SME-B
- [x] Stratanovich: https://link.springer.com/article/10.1007/s10543-007-0130-3
- [x] Adaptive: https://onlinelibrary.wiley.com/doi/abs/10.1002/pamm.200410005

**Comment by ChrisRackauckas** [comment]
Note that for implementing the adaptive schemes, all that needs to be done is the addition of the error estimator: https://github.com/SciML/StochasticDiffEq.jl/blob/master/src/perform_step/sri.jl#L111-L118 . If you notice the implementation of EnsembleGPUArray and EnsembleCPUArray will then automatically use the normed pooled error, so that recovers the scheme of Rossler (the Brownian bridge is handled automatically by the machinery of the package.

**Comment by frankschae** [comment]
Probably, we should also add 

`COM`:
https://www.sciencedirect.com/science/article/pii/S0377042706001737?via%3Dihub
[ simplified version applicable in case of commutative noise ] 

and 

`NON2`:
https://www.sciencedirect.com/science/article/pii/S0377042711002159
[ modified version with lower computational costs ]

**Comment by ChrisRackauckas** [comment]
GG @frankschae
