### ISSUE TITLE
SROCKC2 converges at weak order 1 for only OOP

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/StochasticDiffEq.jl#320]
Whenever someone has a chance this should be an easy one. Out of place converges at weak order 1, in-place at weak order 2. It should be weak order 2. It can be looked at side by side to figure out the error. 

@deeepeshthakur

**Comment by deeepeshthakur** [comment]
@ChrisRackauckas  Can you please mention the example where things are going off. I tried matching the implementation of the two and nothing seems to jump out.

**Comment by ChrisRackauckas** [comment]
It might've just been a testing issue since I marked the test as broken and Travis just came back saying it passed, so hold on: I think it might be good.

**Comment by ChrisRackauckas** [comment]
False alarm.

**Comment by ChrisRackauckas** [comment]
The strong order 1 for non-commutative still needs work though if you're ever around, but that's a hard one!
