### ISSUE TITLE
ArrayPartition with SDE interface

### ISSUE THREAD

**Issue by Lewih** [SciML/StochasticDiffEq.jl#353]
Hi pals!

Is it possible to use ArrayPartition while solving a SDE? 
I tried to implement it in the past for an ODE with no issues, but attempting the same with the SDE interface did not work, therefore I had to implement a EM solver from scratch.

`prob = SDEProblem(f, g, u₀, (0.0, 1.0))`
I'm interested in having this feature both for the main function `f` and the noise function `g` in order to allow the computation of system of equations with arrays as output of each equation.
I'm wondering whether I'm missing something or if it is not possible yet.

I'm available to help the community improving the package if necessary.

Cheers

**Comment by ChrisRackauckas** [comment]
Interesting. It "should" work. What was the issue? We should probably get an example with a test to make sure it works and stays working.

**Comment by Lewih** [comment]
The error
`ERROR: DimensionMismatch("matrix A has dimensions (12,1), vector B has length 2")
`

The error is happening in "perform_step/low_order.jl" line 54, function "perform_step(integrator,cache::EMCache,f=integrator.f)"
Specifically this instruction
`mul!(rtmp1,rtmp2,W.dW)
`
It happens apparently while multiplying the output of `g` with the Normally distributed noise W. The ArrayPartition object is so considered as an array of 12 elements and not as a container of 3 2x2 matrices.

Here the snippet i'm using
```Julia 
W = WienerProcess(0.0, zeros(Complex{Float64}, Ncav))
# using ArrayPartition for heterogeneous arrays 
αuv₀ = ArrayPartition(zeros(Complex{Float64}, Ncav),       # α
                                    zeros(Complex{Float64}, Ncav, Ncav), # u
                                    zeros(Complex{Float64}, Ncav, Ncav)) # v
Gout = ArrayPartition(zeros(Complex{Float64}, Ncav, Ncav),
                                     zeros(Complex{Float64}, Ncav, Ncav),
                                     zeros(Complex{Float64}, Ncav, Ncav))
prob = SDEProblem(sde!, sdeNoise!, αuv₀, (tmin, tmax), p, noise=W, noise_rate_prototype=Gout)
sol = solve(prob, EM(), dt=dt, reltol=1e-6, save_noise=true)
```

https://diffeq.sciml.ai/stable/tutorials/sde_example/#Example-4:-Systems-of-SDEs-with-Non-Diagonal-Noise 
It seems to follow the behaviour showed in the link above without considering the different type of ArrayPartition as it was just interpreting it as an abstractArray and dealing with it as a normal 1D array.

**Comment by Lewih** [comment]
I'm investigating.
In `@muladd function perform_step!(integrator,cache::EMCache,f=integrator.f)` everything else appears to work fine: the cache is consistent with the configured parameters .

Extending the LinearAlgebra package with a specific mul! method may be a solution to the problem and be useful throughout the whole package.

```Julia

import LinearAlgebra
function LinearAlgebra.mul!(C::ArrayPartition, A::ArrayPartition, B::Array)
    @assert length(C.x) == length(A.x)
    for index = 1:length(C.x)
        mul!(C.x[index], A.x[index], B)
    end
end

using DifferentialEquations, SparseArrays

function sde!(dαuv₀, αuv₀, p, t)
    α, β = p
    dαuv₀.x[1] .= αuv₀.x[1] * α
    dαuv₀.x[2] .= αuv₀.x[2]
    dαuv₀.x[3] .= αuv₀.x[3]
end

function sdeNoise!(Gout, αuv₀, p, t)
    α, β = p
    Gout.x[1] .= sqrt(β).*(conj(αuv₀.x[3]).+αuv₀.x[2])
    Gout.x[2] .= αuv₀.x[3]
    Gout.x[3] .= αuv₀.x[2]
end

function simulation()
    α=1
    β=5
    p = (α, β)
    scaling = 2
    dt = 2.0e-3
    W = WienerProcess(0.0, zeros(Complex{Float64}, scaling))
    # using ArrayPartition for heterogeneous arrays computation
    αuv₀ = ArrayPartition(zeros(Complex{Float64}, scaling),
                          zeros(Complex{Float64}, scaling),
                          zeros(Complex{Float64}, scaling)) .+ 1
    Gout = ArrayPartition(zeros(Complex{Float64}, scaling, scaling),
                          zeros(Complex{Float64}, scaling, scaling),
                          zeros(Complex{Float64}, scaling, scaling))
    prob = SDEProblem(sde!, sdeNoise!, αuv₀, (0.0, 100.0), p, noise=W, noise_rate_prototype=Gout)
    sol = solve(prob, EM(), dt=dt, save_noise=true)
end

```

**Comment by ChrisRackauckas** [comment]
This is the right thing to do. ArrayPartition is just missing some linear algebra overloads, and those should go into RecursiveArrayTools

**Comment by Lewih** [comment]
I opened a pull request in the correct repo to start fixing the issue  [https://github.com/SciML/RecursiveArrayTools.jl/pull/113](url)

**Comment by ChrisRackauckas** [comment]
Handled there. Thanks!
